### ISSUE TITLE
JSON number processing

### ISSUE THREAD

**Issue by Wassili-Hense** [nilproject/NiL.JS#104]
Можно ли сделать при конвертации в JSON, если это double, то даже целые числа выводить с точкой?
```
(double)12 => "12.0"
(long)12 => "12"
```
И при обратной конвертации это учитывать.

**Comment by nilproject** [comment]
Спецификация JS для функции JSON.stringify не даёт однозначного ответа о том, допустимы ли незначащие нули после точки. Не думаю, что для этого нужно вносить изменения в реализацию JSON.stringify.
Вместо этого можно в stringify передавать в качестве второго параметра функцию, которая будет приводить числа к нужному представлению. Что-то вроде
```JS
function (key, value) {
  if (typeof value !== 'number')
    return value;

  var result = value.toString();
  if (result.indexOf('e') === -1 && result.indexOf('.') === -1)
    result += '.0';
  return result;
}
```

**Comment by Wassili-Hense** [comment]
> Спецификация JS для функции JSON.stringify

В JSON.NET так сделано.

> Вместо этого можно в stringify передавать в качестве второго параметра функцию

Здесь вопрос производительности вылезает на первое место.
Для обмена данными между сервером и клиентом я оборачиваю их в JSON. Передаётся Integer, а при приёме происходит безусловная конвертация в Double.
Поскольку нужен мне Integer, я делаю (int)js_val. При этом происходит частая конвертация Double=>Integer.
Сама операция достаточно быстрая, но их десятки тысяч в секунду.

**Comment by nilproject** [comment]
Тогда, как я понимаю, проблему стоит решать несколько иначе. Я могу сделать добавление нуля для double, но это не решит проблему, а только замаскирует её. Все числа проходят через функцию Tools.ParseNumber, которая возвращает тип double. Если я начну учитывать наличие нуля, то это, по сути, переместит приведение double->int из вашего кода в код JSON.parse.
Если вы уверены, что проблема с производительностью в обработке чисел и переводе типов из одного в другой, тогда есть смысл поработать над оптимизацией Tools.ParseNumber. Она написана из предположения, что изменение типа представления числа условно бесплатно.
