### ISSUE TITLE
Nuget... tasty beta/pre-release versions...

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#112]
Hi Dmitriy,
Thanks for all the speedy changes and acceptances.
Do you have a CI process to deploy to NuGet? We could really do with having these latest versions deployed as pre-release versions to the official repository to make them easier to test in-situ.

**Comment by nilproject** [comment]
No, I have no CI. Every time before the release, I manually run all tests and manually build the packages for nuget.
I think selection of branch for beta will not be of much benefits, since the library does not so many users. Or the most part of users will go to beta and release will lose its meaning.

**Comment by jsobell** [comment]
Possibly, although at the moment most users will only ever use the NuGet package, so without recent fixes deployed they will always be using buggy or sub-optimal versions.
I suspect that it would not take much to get a much larger usage base of the library. We've been using ClearScriptV8 extensively, but we are looking to optimise the system in two ways:
- Enable system to work on .Net Core under Linux
- Reduce the amount of marshalling between ClearScript and .Net

Both of these require a library like yours, so we are keen to get it up to be an equivalent to ClearScript, and I think that with the error messages and inclusion of `assign` we may be pretty much there.
Currently your library appears to be the only ES6 option available for .Net, so now would be the ideal time to demonstrate it to a wider public audience.
Perhaps we should look at authoring a CodeProject article?

**Comment by nilproject** [comment]
An article on CodeProject would be very useful, it would greatly increase the number of users. But I'm not sure I can write it, because, to put it mildly, мой английский недостаточно хорош.

**Comment by jsobell** [comment]
Ну мой русский еще хуже! (thanks, Google Translate!)
That's fine, I can write up an article :)
Can you send me the nuspec file you use? I'll look at a CI build process to simplify things for you.

**Comment by nilproject** [comment]
Yes, of course. I added this file to repository. https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/NiL.JS.nuspec
