### ISSUE TITLE
Missing `Object.defineProperty`

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#115]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by jsobell** [comment]
An example might be:
`Object.defineProperty(this, 'Sms', { configurable: true, get() { return "Fred"; }});`

The current context should behave as an Object:
![image](https://user-images.githubusercontent.com/834155/37904018-f5d00dd0-3145-11e8-9f9f-6c2a369fc0ad.png)

**Comment by nilproject** [comment]
I runned this code and it works.
```JS
Object.defineProperty(this, 'Sms', { configurable: true, get: function() { return "Fred"; } });
console.log(Sms);
```
Output:
```
Fred
```

But I found a bug, that do not allow to write `get() {}`, only `get: function(){}`. It's only change.

**Comment by jsobell** [comment]
Ah, nice.
This is the main reason we need error messages specifying where the issue is, as a generic error saying "`Object reference not set to an instance of an object.`" isn't enough to know which part of the tree is generating the issue, particularly if it's in the middle of something like moment.js :)
