### ISSUE TITLE
Question re class definitions...

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#116]
It's usually possible to define classes using the following syntax:
```
class MyClass { }
```
In NiL.js the command is received, and displays the defined class but doesn't appear to associate it with the current context, so it's not usable unless assigned to another variable:
```
var MyClass = class MyClass { }

var thingy = new MyClass();
```
Is there a reason this behaviour is different to that of other runtimes?

**Comment by nilproject** [comment]
How you runs this code?
I just tested it. All works as expected
```JS
class MyClass {
  test() {
    return 'Hello';
  }
}

var thingy = new MyClass();
console.log(thingy.test());
```
Output:
```
Hello
```

**Comment by nilproject** [comment]
This behavior is the same as v8 in node.js. 
If you tries to define this class via Context.Eval(..), then pass as second argument `true`. It changes behaviour of creating of nested Contexts.
