### ISSUE TITLE
define Interface in DefineVariable

### ISSUE THREAD

**Issue by alexhome82** [nilproject/NiL.JS#119]
If I define an interface in a variable

           var context = new Context(firstGlobalContext);
            TestJs testJs = new TestJs();
            IMyInterface b = testJs;
            context.DefineVariable("testJs").Assign(JSValue.Marshal(b));
            context.Eval("testJs.b='asdqwe'"); // <----------------------------- THIS WORK !!!!!!!!!!!

 ```
public interface IMyInterface
    {
        string a { get; set; }
    }
    public class TestJs: IMyInterface
    {
        public string a { get; set; }
        public ExpandoObject ex { get; set; } = new ExpandoObject();
        private string h;
        public string b;
        public void Add(string y)
        {
            a += y;
            Console.WriteLine(a);
        }
    }
```
How can i register restricted type ?
And what difference between JSValue.Wrap and JSValue.Marshal?

**Comment by nilproject** [comment]
Javascript do not support Interfaces. You couldn't to define an interface in JS as it is in C#. Also, `Marshal` and `Wrap` uses real classes of value which passed in, not a type of variable, that contains it.

To understand the difference between `Marshal` and `Wrap` see two examples bellow:
[Via Marshal](https://github.com/nilproject/NiL.JS/blob/version-2.5/Examples/2.%20Pass%20values%20into%20JavaScript%20environment/Via%20Marshal.cs)
[Via Wrap](https://github.com/nilproject/NiL.JS/blob/version-2.5/Examples/2.%20Pass%20values%20into%20JavaScript%20environment/Via%20Wrap.cs)
