### ISSUE TITLE
Marshal and Wrap in JS context

### ISSUE THREAD

**Issue by alexhome82** [nilproject/NiL.JS#120]
Please help with some questions:

```
engine.DefineVariable("myCallObject").Assign(JSValue.Marshal(new MyCallObject));

public class MyCallObject {
    public MyRetObject GetClrObject() {
        return new MyRetObject();
    }
    public void TestClrObject(object clrObject) {
          //---------------------------------------------- Can i execute Test() from clrObject ???
    }
        
}
public class MyRetObject {
   public string Str { get; set; }
    public void Test() {
        return new MyRetObject();
    }        
}
```

```
engine.Eval(@"
var obj = myCallObject.GetClrObject(); //------------------ Its Marshal or Wrap
myCallObject.TestClrObject(obj); // ------------------------Execute with Clr Object or JS ?
")
```

**Comment by nilproject** [comment]
Yes, you can execute Test() from clrObject, but you need to change type of this argument with `MyRetObject`, else you get a wrapped value with type JSValue (or some derived type).
Marshal and Wrap for classes gives the same results. You can call methods of classes for results of both these functions.
These methods gives different results for primitive types (int, double, float) and strings.
For example, if you call Marshal for string, you get JS-string (length with lowercase 'l' etc.), but if you call Wrap, you get .NET string, wrapped into special internal class, which provide access to native methods and properties (Length with uppercase 'L'). That's difference.
