### ISSUE TITLE
valueOf on .NET objects?

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#123]
At the moment when we create a class `User` in .NET, when we refer to an instance we always get back `[object User]`, which is not so helpful in instances where we want to dictate what the engine returns when we refer to the object itself.
On a javascript object we have `valueOf` that we can override, so perhaps we need the same thing as an optional override on assigned objects in the same way that `toJSON` is?

**Comment by nilproject** [comment]
`valueOf` is method of `Object.prototype`. i.e. root prototype of all objects in JS. So, you can define method with this name in you class (or use attribute `JavaScriptName`) and it will work. Also you can override `toString()`.
Or did I misunderstand you?

**Comment by jsobell** [comment]
OK, thanks, I did some tests and found that `ToString()`, `toString()` and `valueOf()` all need overriding because each is used in different situations.
