### ISSUE TITLE
Error in the NiL.JS NuGet package

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#125]
The `lib/net45` directory of [NiL.JS package](https://www.nuget.org/packages/NiL.JS/2.5.1230) (version 2.5.1230) contains an assembly, that built for .NET Framework 4.6.1. During building of the project targeted to .NET Framework 4.5, this leads to appearance of the following warning:

```
warning MSB3274: The primary reference "…\.nuget\packages\nil.js\2.5.1230\lib\net45\NiL.JS.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
```

There are two ways to solve this problem:

 1. Put in the `lib/net45` directory a `NiL.JS.dll` assembly, that built for .NET Framework 4.5.
 1. Rename the `lib/net45` directory to `lib/net461`.

**Comment by nilproject** [comment]
Thank you for this bug and sorry for my lag. I fixed the package and upload it on Nuget. Revision should be 1241.

**Comment by Taritsyn** [comment]
Thank you!
