### ISSUE TITLE
There is a way to serialize JValues in dotnetCore ?

### ISSUE THREAD

**Issue by matteofabbri** [nilproject/NiL.JS#126]

**Comment by nilproject** [comment]
Is JValue a Json.NET object? If yes, then just use Json.NET.

**Comment by matteofabbri** [comment]
I was meaning NiL.JS.Core.JSValue so, no is not Json.NET object.

I already tryed Json.NET, with not enthusiastic results:

Newtonsoft.Json.JsonSerializationException: 'Cannot create and populate list type NiL.JS.Core.JSObject. Path '$values', line 1, position 51.'



  ```
var context = new Context();

context.DefineVariable("what");
context.Eval("what = {type:\"Fiat\", model:\"500\", color:\"white\"};");

var val = context.GetVariable("what").Value;

var setting = new JsonSerializerSettings()
{
   //remove this and it will fail due to cycle references
   ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
   TypeNameHandling = TypeNameHandling.All,
    MetadataPropertyHandling = MetadataPropertyHandling.ReadAhead
 };
 var j = JsonConvert.SerializeObject(val, setting);
 var ds = JsonConvert.DeserializeObject(j,setting);
```

**Comment by nilproject** [comment]
Use `NiL.JS.BaseLibrary.JSON` for it. This is the implementation that is available in JS via the JSON variable.
`NiL.JS.BaseLibrary.JSON.parse` and `NiL.JS.BaseLibrary.JSON.stringify`.
