### ISSUE TITLE
Major reworking of build and project structure...

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#129]
OK, well after struggling to find a sensible way of building the project through some form of CI, I created the following branch: https://github.com/questmetrics/NiL.JS/tree/questmetrics
This branch is linked to a MyGet build process that auto-generates a 'pre' version that we use for testing, and creates a single nuget package with .Net 4.5, 4.6.1, and Standard 1.3 created from the same project file.

Check this out, and see if you can see any issues. The tests all run fine (and are included) and the only thing I've ignored is the PORTABLE version because this has now been superseded by .Net Standard.

If you use this structire of project you can send me your email address we can arrange to setup an automated build from your account, which will build, tag, and deploy to NuGet automatically.

For now, if you'd like to test the package, you can see it on our public NuGet feed here: https://www.myget.org/feed/Packages/questmetrics-public
It's based on your latest commit on `develop` branch with my pull-request applied. I've tested it against the date test code I wrote, and it passes all tests.

**Comment by nilproject** [comment]
I need to think about this issue. I do not want to lose features in process of reworking.
Support of Portable can be dropped, it's true.

**Comment by jsobell** [comment]
At some point, if this project is to be taken seriously, it needs to move from being a one-man home-compiled system to one with proper continuous integration and deployment, and a system of beta versions and releases is required.

We are trying to use this in my company as a replacement for ClearScript, and it is almost there, but of course every time we have an issue we create a workaround on our own version and hope that your version will eventually get the same fix.

The current system with symbolic links is not practical and can't be integrated into any CI system. There is also no need for the complexity of multiple solutions, because MSBuild will now generate all multiple deployment targets from a single project. The only complexity is when there are conditional sections in the code (such as the NameSpaceResolver?) which appears to be undocumented and I can't see any mention of why or how it is used.  I'm not sure if any backwards compatibility might be lost by changes such as this, but I'm certain new users will prefer a proper dev/beta/prod deployment process to the current structure. 

We are not new to software development; I have been creating libraries on many platforms since the 1980's, and Binh is a core developer on the Aurelia framework team, so we're very familiar with what people makes people adopt a library, and what scares them off.

**Comment by nilproject** [comment]
Yes, I understand that current solution is very complex. This complexity is explained by the fact that all this was formed over a period of 4.5 years. Of course, in this is to restore order.

About `NamespaceProvider`: there is [example with using it](https://github.com/nilproject/NiL.JS/blob/version-2.5/Examples/5.%20Namespaces%20and%20external%20types/Using%20NamespaceProvider.cs) and I got a some feedback about this class.

**Comment by nilproject** [comment]
I connected Travis CI because it is free and available for viewing by everyone. Let's call it the beginning of big changes. Currently build produces without tests, but It's a question of time. Else it is useless.

**Comment by jsobell** [comment]
Sure, that's fine.
Take a look at the branch I committed and see if there is anything missing that is not in the current release.
`NamespaceProvider` is already in there but is not available in the Core version on your version, only .Net framework. It can be added to Core if we update to above Standard 1.3, but it uses AppDomain features not available in 1.3.

**Comment by viceice** [comment]
@nilproject Any news on this? I can send a pr to refactor to a single solution without symlinks.

We currently started on heavily using this project and found some bugs. We don't want to maintain a fork. Any chances to get things done?

**Comment by nilproject** [comment]
You motivated me to do it. See afe285b392f2abd238a4be86c990b0da7a7c05bf
