### ISSUE TITLE
Several places `JSValueType.notExists` is not handled

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#138]
There are a number of places where select-case handlers look at most datatypes but omit notExists.
One issue is that functions such as `Equals` fails when trying to compare things like a function returning a null string. If the object in the comparison is notExists the case drops through to a not implemented exception.
If a .NET object call returns a null it seems to be being treated as a notExists JSValue, so exceptions are thrown.
E.g. I have a class `User`, with a function `public string GetBigHugs() { return null; }`
`Eval("myuser.GetBigHugs() == "Yes please")` crashes with a `NotImplementedException`

**Comment by nilproject** [comment]
Thanks for this bug report!
