### ISSUE TITLE
There is a reason why stuff should not be serializable on Core ?

### ISSUE THREAD

**Issue by matteofabbri** [nilproject/NiL.JS#149]
As example :
    
    //EvalError.cs
    #if !(PORTABLE || NETCORE)
        [Serializable]
    #endif
    public sealed class EvalError : Error

**Comment by nilproject** [comment]
Because of this mechanism of serialization is deprecated in Net Core.
https://stackoverflow.com/questions/39199049/what-is-the-equivalent-of-serializable-in-net-core-conversion-projects
