### ISSUE TITLE
Behavior of NilJS with Dictionaries (generic and non-generic) - what to expect

### ISSUE THREAD

**Issue by lafar6502** [nilproject/NiL.JS#153]
Hi, i cant find a documentation of how Dictionary (IDictionary) object is treated by NilJS - should it be converted to javascript object or not?

when i test it it appears dictionary is not treated like javascript object - i can't access dictionary values like js object properties

And a question - how to convince Nil.JS to treat .Net dictionaries like javascript objects?

the test - here all attempts to access dictionary contents via JS return empty result (NotExistsInObject)
```
            var ctx = new NiL.JS.Core.Context();

            var dic = new Dictionary<string, object>
            {
                {"a", "b" }, {"c", 150 }
            };
            ctx.DefineVariable("dic1").Assign(JSValue.Marshal(dic));
            ctx.DefineVariable("dic2").Assign(JSValue.Wrap(dic));
            
            var r0 = ctx.Eval("dic1.a");
            var r1 = ctx.Eval("dic2.a");
            var r2 = ctx.Eval("dic1['a']");
            var r3 = ctx.Eval("dic2['a']");
```

**Comment by nilproject** [comment]
Hi! No, Dictionaries are not converted to JS object. Instead of this, use `ExpandoObject`. See `NiL.JS.Core.Interop.ExpandoObjectWrapper`.

**Comment by lafar6502** [comment]
ok thx
