### ISSUE TITLE
Using decimal.js with Nil.js, possible parse error/bug in nil.js?

### ISSUE THREAD

**Issue by KodaPOwER** [nilproject/NiL.JS#158]
Hello,

I'm using decimal.js in nil.js with good results. But i have a strange behavior.

If i run this code:
var js = new NiL.JS.Module("var result = new Decimal(10.02);");
            js.Context.Eval(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\decimal.js")));
            js.Run();
            var result = js.Context.GetVariable("result");
            Console.WriteLine(result.Value);
result.Value is 10.0065536

Instead in chrome console:
![image](https://user-images.githubusercontent.com/9638822/50827882-0f7a0380-1340-11e9-9c86-be749b13fbfd.png)

If i run:
var js = new NiL.JS.Module("var result = new Decimal(10.12);");
            js.Context.Eval(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\decimal.js")));
            js.Run();
            var result = js.Context.GetVariable("result");
            Console.WriteLine(result.Value);
result.Value is 10.12 as expected

All other values are correct. this problem occur only if the first decimal digit is 0.

It's a parse bug of Nil.js while executing some code of Decmal.Js?
I don't think is a decimal.js bug because in chrome console it works...

Edit:
I've attached a sample project that show the issue.
[TestDecimalJs.zip](https://github.com/nilproject/NiL.JS/files/2736529/TestDecimalJs.zip)

**Comment by nilproject** [comment]
Thanks for this bug report!
