### ISSUE TITLE
Destructuring assignment is not implemented

### ISSUE THREAD

**Issue by b2ox** [nilproject/NiL.JS#159]
> var context = new Context();
> context.Eval("var [a,b] = [0,1]");

> var context = new Context();
> context.Eval("var {x,y} = {x:0, y:1}");

In both cases the following exception occurs:
> System.InvalidOperationException: initializers.Count != variables.Length

**Comment by nilproject** [comment]
Thanks for this bug report!
I assume, I made best fix for this.
