### ISSUE TITLE
Setter for byte Property NullReferenceException

### ISSUE THREAD

**Issue by Nerixyz** [nilproject/NiL.JS#171]
The setter for byte Properties throws a NullReferenceException.
Code:
```
class Test
        {
            private byte _dimmer = 0;
            private bool dirty = false;
            public byte Dimmer { get => _dimmer; set {
                    _dimmer = 0;
                    dirty = true;
                } }

            public Test(byte dimmer)
            {
                this._dimmer = dimmer;
            }
        }
void Eval(){
            Context ctx = new Context();
            ctx.DefineConstructor(typeof(Test));
            ctx.Eval(@"var test = new Test(3);
            test.Dimmer = 0;
            console.log(dimmer);");
} 

```
It breaks at `test.Dimmer = 0` .
The exception: 
`System.NullReferenceException: Object reference not set to an instance of an object.    at set_Dimmer(Closure , Object , Context , Expression[] , Arguments )    at NiL.JS.Core.Functions.MethodProxy.invokeMethod(JSValue targetValue, Expression[] argumentsSource, Arguments argumentsObject, Context initiator)} `

**Comment by nilproject** [comment]
Thank you for this bugreport!
