### ISSUE TITLE
Unintended result when using operators on wrapped/marshalled Managed types.

### ISSUE THREAD

**Issue by bilenkonito** [nilproject/NiL.JS#175]
Using arithmetic or equality operators on managed types wrapped or marshalled into JS results in unintended behaviour.
This is specially painful for arithmetic-heavy types like vectors, which force you to do things like `vec1.Add(vec2)` rather than `vec1 + vec2`

Would it be possible to marshal/wrap operator overloads along with the types?

**Comment by nilproject** [comment]
Short answer: no. Operators overloading is not supported in JS.

Long answer: yes, but it is required to make incompatible changes. You can fork this repo and make suitable changes in `NiL.JS/Expressions`. I assume, the most correct way is to implement full support of that types like an other embedded types.
