### ISSUE TITLE
ConstructorProxy should filter non-public constructors

### ISSUE THREAD

**Issue by bilenkonito** [nilproject/NiL.JS#176]
`ConstructorProxy.cs:70`
```csharp
ConstructorInfo[] array = (ConstructorInfo[]) Enumerable.ToArray<ConstructorInfo>((IEnumerable<M0>) staticProxy._hostedType.GetTypeInfo().DeclaredConstructors);
```

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.typeinfo.declaredconstructors?view=netframework-4.8

Non-public constructors are returned from DeclaredConstructors and NiL.JS does not filter them. This means it is impossible to hide constructors from the JS context and, more importantly, that types expected to be injected into the JS context cannot 1) be unsafe and/or 2) contain "ref" parameters/returns because of the use of LINQ Expressions in MethodProxy.

I am aware that HiddenAttribute can be used to hide the constructor but that requires that NiL.JS be referenced by the assembly declaring the type to be injected, which completely invalidates any plug-in pattern approach.

**Comment by nilproject** [comment]
Thank you for this bugreport.
