### ISSUE TITLE
Add changelog to repository and release notes to nuget package

### ISSUE THREAD

**Issue by Markeli** [nilproject/NiL.JS#178]
Hi! 
We are using `Nil.JS` in production at the important part of our software. Updates of your package are very useful for us. But we need to go to commits and analyze what was changed. Can your please add changelog to your repository with short description about changes ([here](https://keepachangelog.com/en/1.1.0/) are the recommendations followed by many projects on github) and some release notes or link to changelog in nuget package?

**Comment by ghost** [comment]
+1. We would appreciate

**Comment by nilproject** [comment]
Hi!

Thanks for suggestion!
