### ISSUE TITLE
Problem when finding json serializer if other serializers have large inheritance tree

### ISSUE THREAD

**Issue by rmja** [nilproject/NiL.JS#190]
I am having trouple understanding the algorithm for finding the correct serializer to use when invoking JSON.stringify()

Consinder the following screenshot from a debug session:

![image](https://user-images.githubusercontent.com/2112306/66192131-1eec6a00-e690-11e9-9bbf-a905cc599f53.png)

There are 5 registered serializers. It seems as if serializers, when registered, are associated with a weight, determined from the inheritance distance from the type they can serialize. Serializer 0 and 4 are registered for plain types that does not inherit from anything (but object). Serializer 1, 2, and 3 has a target type that derives from other types.

In this session, I am trying to get the serializer for the target type registered for serializer 0, but the algorithm does not find it. `indexMore=2` and `indexLess=3` at the current position, but the desired serializer is at index 0.

The problem has arised after the weights have changed. Before I had the target types for 1-3 not deriving from anything, so all weights were 1. Back then, everything worked. But after their base type has changed, the serializer is not found.

**Comment by rmja** [comment]
The following is the order in which the serializers are added:

```
            new InteropJsonSerializer(typeof(QueryResultObject)), // Weight 1
            new InteropJsonSerializer(typeof(QueryDetailsObject)), // Weight 1
            new InteropJsonSerializer(typeof(DataObject)), // Weight 1
            new InteropJsonSerializer(typeof(OriginObject)), // Weight 4
            new InteropJsonSerializer(typeof(SampleObject)) // Weight 4
```

If I swap this order so that the target types with the heighest weight is added first, then things seems to work:
```
            new InteropJsonSerializer(typeof(OriginObject)), // Weight 4
            new InteropJsonSerializer(typeof(SampleObject)), // Weight 4
            new InteropJsonSerializer(typeof(QueryResultObject)), // Weight 1
            new InteropJsonSerializer(typeof(QueryDetailsObject)), // Weight 1
            new InteropJsonSerializer(typeof(DataObject)) // Weight 1
```

**Comment by nilproject** [comment]
Thanks for this bug report.

What function you for getting serializer? There are two functions: `GetJsonSerializer` and `GetSuitableJsonSerializer`. They have some significant differences.

**Comment by rmja** [comment]
I am not getting it explicitly, but implicitly via JSON.stringify. I think
it calls GetSuitableJsonSerializeras far as I remember.


tir. 8. okt. 2019 17.49 skrev Дмитрий <notifications@github.com>:

**Comment by nilproject** [comment]
Yes, it calls `GetSuitableJsonSerializer`
