### ISSUE TITLE
How to properly reuse a compiled Script

### ISSUE THREAD

**Issue by rmja** [nilproject/NiL.JS#192]
I am trying to achieve the best possible execution speed for some common scripts.
To do this, I have precompiled them with `Script.Parse`, cached them in memory, and reused them in different contexts.

But I think that I am missing something here, because it seems as if an execution "leaks" into the script instance with e.g. variables.

So, to clearify, can a Script instance be considered immutable and thread-safe, and is it designed to reused in different contexts?

**Comment by nilproject** [comment]
"is it designed to reused in different contexts?": Yes. You can use it in different contexts. This was the main goal when creating.

"can a Script instance be considered immutable and thread-safe": No, `Script` is not thread-safe. Like `Function` gotten via something like `Context.GetVariable`. Due some optimizations AST is not thread safe. Many `CodeNode`s uses [_tempContainer](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Expressions/Expression.cs#L15). This is the main reason.

As a solution, you can make pool of `Script`s and use it in multithread scenarios.

**Comment by rmja** [comment]
Ok, thanks. But how do I properly clear/reset the Script instance before re-inserting it in the pool?

**Comment by nilproject** [comment]
It's not needed. All state stored in `Context`. Internal caches of `Script` clears automatically

**Comment by rmja** [comment]
Perfect, thanks! I have created a cache of Script pool's, one for every precompiled script.
