### ISSUE TITLE
Using Script vs Module yields different result

### ISSUE THREAD

**Issue by veremenko-y** [nilproject/NiL.JS#195]
I want to use `Script` to avoid parsing of the scripts we have every time. I tool a look at the `Module` implementation, and I think reproduced it properly. But I have no idea why using `Script` object yields empty context as opposed to using `Module` or `Context.Eval(...)`.

```
    var path = @"c:\path\to\example.js";
    
    var context = new Context();
    var script = Script.Parse(File.ReadAllText(path));
    script.Evaluate(context);
    // context is empty     
    
    var module = new NiL.JS.Module(File.ReadAllText(path));
    module.Run();
    // module.Context as expected
```

**Comment by rmja** [comment]
Can you post the js file that causes this so that I can try and reproduce.

**Comment by veremenko-y** [comment]
Thank you. It is as simple as this.

    function configure(config) {
    }

    function execute(ctx) {
    }

Exact test code:

    var path = @"c:\temp\example.js";
    
    var context = new Context();
    var script = Script.Parse(File.ReadAllText(path));
    script.Evaluate(context);
    Console.WriteLine(context.Count()); // prints 0
    
    var module = new NiL.JS.Module(File.ReadAllText(path));
    module.Run();
    Console.WriteLine(module.Context.Count()); // prints 2

**Comment by rmja** [comment]
But you are not assigning anything to the context from the script. Try and assign a variable, and you will see it.

**Comment by veremenko-y** [comment]
But I do. I'm declaring two functions. If I run it with `Context.Eval` I get what I want.

    var context = new Context();
    context.Eval(File.ReadAllText(path));
    // I can get the function and execute it
    context.GetVariable("configure").As<Function>().Call(new Arguments { commandCondext });
    // I can iterate trough the declared items in the context
    foreach(var variable in context)
    {
        Console.WriteLine(variable);
    }
    /* Output
    configure
    execute
    */

**Comment by rmja** [comment]
Now I know what is going on. Try and set the options parameter on the the Script.Parse parameter with the SuppressUseless... The problem is that you never use the functions, so they are not included in the compiled script.

**Comment by veremenko-y** [comment]
Yes, because I want to declare them and then call them from c#. Unfortunately even if I set all the flags, it still returns empty context.

	var script = Script.Parse(File.ReadAllText(path), null,
		Options.SuppressConstantPropogation | 
		Options.SuppressUselessExpressionsElimination | 
		Options.SuppressUselessStatementsElimination);

**Comment by nilproject** [comment]
Thanks for this report. Thanks @rmja for trying to understand. It's really bug. It's too hard for describe how it works and why `Module` and `Script` differs in this scenario, but I can say that this is consequence of some complex optimization.
Fix of this takes 2 line of code in `Script`

**Comment by veremenko-y** [comment]
Thanks a lot for a such a quick fix @nilproject  !
