### ISSUE TITLE
System.DivideByZeroException

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#201]
Error appears only in my environment. Code looks like:

> var context = new Context();
> var param = new { OddAmount = -1, RRN = (string)null };
> context.DefineVariable("param").Assign(JSValue.Marshal(param));
> var result = context.Eval("param['OddAmount'] >= 0 || param['RRN'] != null");

Callstack:

>   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
>    at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
>    at NiL.JS.Expressions.ExpressionTree.parseContinuation(ParseInfo state, Expression first, Int32 startIndex, Int32& i, Boolean& root, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean forForLoop)
>    at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
>    at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index)
>    at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
>    at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index)
>    at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
>    at NiL.JS.Core.Context.Eval(String code, Boolean suppressScopeCreation)

Error appears in this line of method parseOperand:

> if ((n = (int)d) == d && !double.IsNegativeInfinity(1.0 / d))

**Comment by nilproject** [comment]
Thanks for this bug report! Please, check my fix and close this task if error do not appear
