### ISSUE TITLE
[FEATURE] Optional Chaining & Nullish Coalescing 

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#204]
Hi,

I would like to implement new operators `?.` and `??`. Are there any other helpful references other than the current example?

Typescript 3.7 already supports it. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

# Optional Chaining
```js
if (foo?.bar?.baz) {
    // ...
}
```

# Nullish Coalescing
```js
let x = foo ?? bar();
```

# Workaround

Downlevel compile javascript with typescript compiler before using.

**Comment by viceice** [comment]
Is it possible to to do this with a `CustomCodeFragment` ?

**Comment by nilproject** [comment]
Alas, no. Binary operators can't be implemented with `CustomCodeFragment`.
I will make this soon.

**Comment by viceice** [comment]
ok, thanks. so i'll go the typescript transpile way for now.

**Comment by nilproject** [comment]
I implemented the Nullish Coalescing in 81fd8c4f4bfda856c84d1a6abdbc0fac03773142 but not Optional Chaining. Optional Chaining at current moment is experimental feature. It will be implemented after spec stabilization

**Comment by viceice** [comment]
Ok thanks.

**Comment by viceice** [comment]
Optional chaining is now stage 4. 🥳🥳

https://github.com/tc39/proposal-optional-chaining

**Comment by viceice** [comment]
@nilproject Any chances to get this soon? It would make code much more readable. 🙃

**Comment by nilproject** [comment]
Sorry for my lag. I will make it soon

**Comment by nilproject** [comment]
Implemented in just uploaded 2.5.1544

UPD: Sorry, i missed one commit. See 1545

**Comment by viceice** [comment]
Thank you.
