### ISSUE TITLE
[BUG] missing module constructor

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#205]
According to the source code i should be able to create a `Module` with a pre-parsed `Script`, but the published `NiL.JS` version does not contain that constructor.

https://github.com/nilproject/NiL.JS/blob/8f95c548f05644d498d318980c5545139796914e/NiL.JS/Module.cs#L153

Im using latest version from [nuget](https://www.nuget.org/packages/NiL.JS.NetCore).

**Comment by viceice** [comment]
Looks like prs #197 and #199 are missing in current release. 😢

**Comment by nilproject** [comment]
Outdated
