### ISSUE TITLE
Convert to Delegate with Dynamic Parameter Count

### ISSUE THREAD

**Issue by zacbre** [nilproject/NiL.JS#211]
I'm looking to write the following code:

```
// js
var func = function(arg1, arg2) { ... }
```

```
// C#
var action = func.MakeDelegate(typeof(Func<JSValue[],JSValue>));
action.DynamicInvoke(new List<JSValue>{ "item1", "item2" }.ToArray());
```

Unfortunately, I noticed that MakeDelegate does not break out the array of items that I pass with DynamicInvoke, and instead just passes it in as an array of items for `arg1` in the javascript. `arg2` ends up being null. What I'm trying to figure out is how to pass in the array, without knowing the parameter count.

Any ideas?

Thanks!

**Comment by nilproject** [comment]
Sorry for a late reply.

You can make your own wrapper as in example below:
```
context.Eval(@"function f(...args) { return args.length }");

var f = context.GetVariable("f").As<Function>();

var myFoo = new Func<JSValue[], JSValue>((args) =>
{
    var argsObj = new Arguments();
    foreach (var v in args)
        argsObj.Add(args);

    return f.Call(argsObj);
});

var length = myFoo(new JSValue[] { 1, 2, 3, 4, 5, 6 }).As<int>(); // 6
```
