### ISSUE TITLE
Feature request: Dynamic import

### ISSUE THREAD

**Issue by rmja** [nilproject/NiL.JS#212]
I would like to dynamically resolve some resources with [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) :

```
export default class Builder {
    async build(model) {
        let obj = await import('resourceName');
        return obj.name;
    }
}
```

This throws: 

```
NiL.JS.Core.JSException : SyntaxError: Unexpected token (4:19)
```

Is it possible in some way to support this? I thought that I could simply define `import` on the global context, but that clearly does not work as the parser throws.

**Comment by nilproject** [comment]
You can remove [this line](https://github.com/nilproject/NiL.JS/blob/80aa9278812a5203cede389f6c3d3d1dcda7bc6e/NiL.JS/Core/Parser.cs#L370), but this is not consistent with the specification of [ecma 6.0](https://www.ecma-international.org/ecma-262/6.0/#sec-keywords).

**Comment by IntranetFactory** [comment]
ES2020 defines dynamic imports (see https://v8.dev/features/dynamic-import or https://dev.to/mushfiqweb/top-new-javascript-features-introduced-in-es2020-2d23).    
   
dynamic import is unfortunately a requirement for my current project. Do you plan to add dynamic import and/or would you be open for a PR?
