### ISSUE TITLE
Destructuring assignment fails

### ISSUE THREAD

**Issue by ericvana** [nilproject/NiL.JS#214]
Running the following results in a `IndexOutOfRangeException`:
```
var context = new Context();
context.Eval(@"const test = { a: 1, b: 2 };
const { a, b } = test;
console.log(a, b);");
```
I'm using package version 2.5.1440

Eric

**Comment by nilproject** [comment]
Thanks for this bug report!

**Comment by ericvana** [comment]
Hi,

Using the latest develop version from github, the exception is gone, but the console.log returns `undefined undefined` instead of `1 2`.
Changing the const in `const { a, b } = test;` to `let` or `var` return the expected values.

Eric

**Comment by nilproject** [comment]
So, as I can see, `const` is completely broken. I will fix it soon
