### ISSUE TITLE
Assignment error

### ISSUE THREAD

**Issue by paulushub** [nilproject/NiL.JS#215]
The following is sample code found on Mozilla site for listeners: [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)
```js
class SomeClass {

  constructor() {
    this.name = 'Something Good';
  }

  register() {
    const that = this;             // **<--- Error Here**
    window.addEventListener('keydown', function(e) { that.someMethod(e); });
  }

  someMethod(e) {
    console.log(this.name);
    switch(e.keyCode) {
      case 5:
        // some code here...
        break;
      case 6:
        // some code here...
        break;
    }
  }

}

const myObject = new SomeClass();
myObject.register();
```
Running this in NiL.JS gives error on the line shown above `const that = this;`. Changing this line to `let that = this;`, it works.
What is the rule being enforced here? or is this a bug?

**Comment by nilproject** [comment]
This is the same bug as described in #214
