### ISSUE TITLE
[BUG] undefined const return

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#234]
A defined constant is returned as `undefined` when using short object creation:

```js
function run() {
    const pi = Math.PI;
    const e = Math.E;

    return { pi: pi, e };
}

const v = run();
console.dir(v);
assert(v.pi === Math.PI, `Should be pi but is: ${v.pi}`);
assert(v.e === Math.E, `Should be e but is: ${v.e}`);
```

- `v.pi` is `Math.PI`
- `v.e` is `undefiend`

related to #220

**Comment by viceice** [comment]
- https://github.com/viceice/niljs-testing/blob/0732e6a3ce4820682024e09d6240f010753f0a1a/test/process/main2.js#L1-L14
- https://github.com/viceice/niljs-testing/blob/0732e6a3ce4820682024e09d6240f010753f0a1a/test/Tests.cs#L70-L78

**Comment by nilproject** [comment]
Thanks!

**Comment by viceice** [comment]
Does it work  in lamda too?

When to expect a release?

**Comment by nilproject** [comment]
Yes, it should. Bug is not related to classes or something. This is optimization bug.

Release will be in 15 minutes if you ask.

**Comment by viceice** [comment]
Would be nice to have a release soon, So we can remove the workarounds and don't need new. SImply safe time and cleans up code. 😅

**Comment by nilproject** [comment]
Build 1480 uploaded

**Comment by viceice** [comment]
thanks, already sugested by [renopvate](/renovatebot/renovate] 😅 

As expected my test is now failing, because the value is no longer undefined.
https://github.com/viceice/niljs-testing/actions/runs/664921617
