### ISSUE TITLE
ReferenceError: Variable "setTimeout" is not defined ?

### ISSUE THREAD

**Issue by KaivnD** [nilproject/NiL.JS#240]
```cs
static void Main(string[] args)
{
    var mainModule = new Module(@"
    setTimeout(() => console.log(1), 3000);
    ");
    mainModule.Run();

    Console.ReadLine();
}
```

**Comment by nilproject** [comment]
It's not standard built-in api https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

**Comment by KaivnD** [comment]
OK, thanks, I know that, but how can I implement something like `setTimeout` method, is `System.Threading.Thread.Sleep` ok for this ? @nilproject

**Comment by nilproject** [comment]
I think, `Sleep` is not suitable method for it. Maybe something like `Task.Delay(timeout).ContinueWith(value)`.

**Comment by KaivnD** [comment]
thanks pal

**Comment by deandob** [comment]
@nilproject Any ideas how to implement a sleep function inside the script, it seems setTimeout is the only way to do sleep in JavaScript and as mentioned above its not part of the standard language. Is it possible to do something like a Nil.JS specific extension or add a setTimeout function like how Node.JS does it? 
We have a use case for implementing a loop that needs to run once a second but have no way to create a delay between invocation of each function which overloads our system.

**Comment by nilproject** [comment]
I would create a class with a `SortedDictionary<DateTimeOffset, Action> jobs`, something like `Task worker` and `object lock`.
This class should has the public method `Enqueue(Action, DateTimeOffset)`, which locks `lock`, adds this action into `jobs` and creates a new worker if current is null or completed.
This class has the method `DequeueAndRun` which peeks at the first job of `jobs` and evaluates it if key is less or equal DateTimeOffset.Now.
The worker is just a loop with calling of `DequeueAndRun`, sleeping and condition `jobs.Count > 0`.
So, this will be your simple event queue or something alike.

**Comment by deandob** [comment]
Thanks @nilproject . To clarify the event queue is implemented in C# and I update the Nil.JS code for this to be a custom function that can be called from a script to create a wait (without using CPU resources while waiting)?

**Comment by nilproject** [comment]
Yes, in C#. No changes required, easier way is to use `GlobalContext.DefineVariable`.
Also, i have found my old implementation of `setTimeout`, it's unsafe, **do not use it in production code**


![image](https://github.com/nilproject/NiL.JS/assets/6096342/0d6b6149-f333-4570-a9a6-13ac7a0a4be9)

**Comment by deandob** [comment]
Helpful as always @nilproject  thank you!
