### ISSUE TITLE
[BUG] IndexOutOfBounds in NativeList

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#241]
This comparision needs an update:
https://github.com/nilproject/NiL.JS/blob/23d202003351698015465b5c1c9cf23582ac2b21/NiL.JS/Core/Interop/NativeList.cs#L309

should be: 
```cs
  if (index < 0 || index >= data.Count) 
```

**Comment by nilproject** [comment]
Thanks for this bug report!
