### ISSUE TITLE
'Invalid export name' when exporting default

### ISSUE THREAD

**Issue by olliejm** [nilproject/NiL.JS#245]
I'm trying to import a library ([date-fns](https://date-fns.org/)) which has statements like the following in the `index.js` of its ESM implementation:

```js
export { default as add } from "./add/index.js";
```

This causes an 'Invalid export name' exception, from stepping through the code it seems that 'default' is detected as a reserved word, causing the exception

**Comment by nilproject** [comment]
Thanks for this bugreport!
