### ISSUE TITLE
BUG: `Arraybuffer` can't be assigned to `byte[]`

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#263]
I'm passing a dotnet object with a `byte[]`  property to the engine and try to assign an `ArrayBuffer` to it.

But the result is now `null` on `v2.5.1532`, same code is working fine on `v2.5.1514`

**Comment by viceice** [comment]
I assume https://github.com/nilproject/NiL.JS/commit/a85f852f68c1e9c45dac6d88aeb985f5d8a31850 is the cause

**Comment by viceice** [comment]
Added a Reproduction here:

https://github.com/viceice/niljs-testing/blob/ac669b58eb548d4ce099736ff02db6dcd379694a/test/Tests.cs#L116

**Comment by viceice** [comment]
https://github.com/nilproject/NiL.JS/blob/7ed8657702451af7a77b3660b6e753b8847478e8/NiL.JS/Core/Tools.cs#L756-L780

cast to `BaseLibrary.Array` at L777 fails for `ArrayBuffer`

**Comment by nilproject** [comment]
Oh, my code in this function need to be rewritten. There are more than one bug in this place, as i can see. What did i think about when writing this?
