### ISSUE TITLE
Transpilation with typescript compiler produces incorrect result

### ISSUE THREAD

**Issue by rmja** [nilproject/NiL.JS#268]
Hi,

I have made the following example project: https://github.com/rmja/NilTypescriptExample
The typescript compiler does not produce the same result when run through Nil.JS compared to V8. Specifically, the private member variable `ss` is not assigned `this` in the constructor as expected.

**Comment by viceice** [comment]
🤔  Strange, maybe this is related to #265 ? Is the typescript compiler using `Set` ?

here are some of my experiments: https://github.com/viceice/dotnet-ts-testing

**Comment by rmja** [comment]
@viceice It is as far as I can tell. Nice comparison by the way. You should put the runtimes in the readme so that one can easily compare the engines.

**Comment by viceice** [comment]
I've looked into your typescript compiler and it's really using Map and Set. So try out latest nil.js release from  https://github.com/nilproject/NiL.JS/releases/tag/2.5.1545

**Comment by viceice** [comment]
> @viceice It is as far as I can tell. Nice comparison by the way. You should put the runtimes in the readme so that one can easily compare the engines.

Feel free to open an issue or pr on that repo, don't have much time  for it 😉

**Comment by rmja** [comment]
I am using 2.5.1545 (https://github.com/rmja/NilTypescriptExample/blob/master/NilTypescriptExample/NilTypescriptExample.csproj#L19)

**Comment by viceice** [comment]
Which typescript version are you using? I've some issues with the new typescript v4.5.2 on Jint, maybe Nil.JS is also hit by this

**Comment by viceice** [comment]
version v4.4.4 of typescript works fine

**Comment by rmja** [comment]
I have tried both typescript 4.2 and 4.4. Both of them produces the wrong transpiled js code when invoked through Nil.JS

**Comment by viceice** [comment]
OK, can confirm the issue at 
- https://github.com/viceice/dotnet-ts-testing/pull/181

**Comment by nilproject** [comment]
That rare case when I used the built-in debugging mechanisms. Not as good as I thought, but good enough to fix this bug.

**Comment by viceice** [comment]
I see, another bug in `Set`, when we can expect a new release 🙃

**Comment by nilproject** [comment]
Just uploaded
