### ISSUE TITLE
Spread operator not working on objects

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#271]
`context.Eval(@"{ ...{ a: 1}, ...{b: 2}}");` is expected to return
```json
{ "a": 1, "b": 2 }
```
but gives an error `SyntaxError: Unknown identifier "...{" at (1:3)`
Spread works for simple array functions such as `math.max(...[1,2,3,4])`

**Comment by nilproject** [comment]
Will be in coming release

**Comment by nilproject** [comment]
new release just uploaded
