### ISSUE TITLE
As() not deserializing a Guid from a string

### ISSUE THREAD

**Issue by savissimo** [nilproject/NiL.JS#273]
Hello everyone, I just noticed that, if a JS variable has a Guid in form of a string (`'01234567-89ab-cdef-0123-456789abcdef'`), when I try to get it out using `GetVariable("foo")` into a type that has a property with that name of type `Guid?`, then I always get `null` for that property. Can I automatically have that string converted to a Guid, or should I do it by hand?

**Comment by savissimo** [comment]
I've just tried a local build with the pull request you accepted from me, and I confirm the issue is fixed. While I could publish my version on a private repository, I'd like to ask when a new release is planned.

**Comment by nilproject** [comment]
In few hours

**Comment by savissimo** [comment]
Great! Thanks a lot!
