### ISSUE TITLE
return await of a C# delegate executes twice

### ISSUE THREAD

**Issue by olliejm** [nilproject/NiL.JS#278]
There seems to be a bug where, when marshalling an async function into Nil.Js from C#, that doing `return await` of that function from inside Nil.Js causes the function to execute twice

I created a minimal reproduction in the unit tests of this fork:
https://github.com/olliejm/NiL.JS/commit/d32999d72a964ce131d2f3b60dc3df108c30f0c7

After executing `wrappedExecutesOnce`, the `executionCount` is as expected, `1`. After execution of `wrappedExecutesTwice` however, the `executionCount` goes up not to `2`, but instead to `3`.

I didn't yet verify if this affects only async functions or all `return func()`.

Not sure if I really placed my unit test in the right place or structured it correctly to keep as a unit test but it does allow to reproduce the problem

**Comment by nilproject** [comment]
Thank you for this bugreport. I have taken your test code for this fix.
So, this fix is about one word
