### ISSUE TITLE
Fail to run on Mono

### ISSUE THREAD

**Issue by nilproject** [nilproject/NiL.JS#28]

**Comment by aienabled** [comment]
Any progress with it? I'm very interested in the project, but only if it can be used on Mono.
Regards!

**Comment by nilproject** [comment]
It is possible to run on Mono. But, need to rewrite all methods of Array.prototype, may be, something else. AllowUnsafeCallAttribute will not work anyway. It is platform limitation

**Comment by nilproject** [comment]
Fixed long time ago
