### ISSUE TITLE
Readonly global context.

### ISSUE THREAD

**Issue by anri-vin** [nilproject/NiL.JS#281]
Is there any way to make a global context completely immutable? For example, I can create one global context with commonly used objects (like enums) and common functions and then I can use it when creating individual contexts for each user in my app. The problem is that any user can rewrite objects and modify data in this global context. In my opinion it breaks the idea of a global context, when user can execute any custom script. So is there any way to protect a global context from any changes after it's been created and configured? Or maybe you have plans of implementing it?

**Comment by nilproject** [comment]
There is no way to add or remove variables to the GlobalContext from insede a script. So, you need to protect variables already added to GlobalContext. To do this you can use `Object.seal()` on each variable. Even if i make some method to protect the GlobalContext, it will be written with `Object.seal()`

**Comment by anri-vin** [comment]
Thank you for you suggestion. As I can see `Object.freeze()` is even more suitable in my case.

**Comment by anri-vin** [comment]
But I still have trouble implementing it. Take a look at my example:
```csharp
private const string Script = @"
    console.log(sampleObj.prop);
    sampleObj.prop = 0;
    console.log(sampleObj.prop);
    sampleObj = 0;
    console.log(sampleObj.prop);";

public static void Main()
{
    var jsObject = JSObject.CreateObject();
    jsObject["prop"] = 42;
    JSObject.freeze(new Arguments() { jsObject });

    var globalContext = new GlobalContext();
    globalContext.DefineVariable("sampleObj").Assign(jsObject);

    Console.WriteLine("First context:");
    var firstContext = new Context(globalContext);
    firstContext.Eval(Script);

    Console.WriteLine("\nSecond context:");
    var secondContext = new Context(globalContext);
    secondContext.Eval(Script);
}
```

I expect to get the same result at each line. But actual output is:
```
First context:
42
42
undefined

Second context:
undefined
undefined
undefined
```

So i'm actualy changing frozen object in global context and it reflects all other contexts created on top of it. So is there a bug, or am I doing/understanding something wrong?

**Comment by nilproject** [comment]
This is not a bug. Object frozen and this is why `sampleObj.prop = 0` does not change the value of `sampleObj.prop`. But there is nothing about variable `sampleObj`, which defined in `globalContext`. So, after `sampleObj = 0` this variable contanins value `0`, and this is becouse `sampleObj.prop` is `undefined`

**Comment by anri-vin** [comment]
Ok, that's reasonable. But how can I prevent `sampleObj` in global context from being overwritten?

**Comment by nilproject** [comment]
Hm, there really is no way to do this. So, I will think about this

**Comment by nilproject** [comment]
Since version 2.5.1622 you can use `Context.DefineConstant(...)` (new) and `Context.DefineGetSetVariable(***, () => value, null)` (bugfix)

**Comment by anri-vin** [comment]
Thanks!
