### ISSUE TITLE
Eval ignore null value properties 

### ISSUE THREAD

**Issue by mahensingh** [nilproject/NiL.JS#282]
context.DefineVariable("inputData").Assign("{ \"fname\": \"test\", \"lname\": null }");
 context.DefineVariable("result").Assign(string.Empty);
 
 var script = "const input = JSON.parse(inputData); result = JSON.stringify(input);"

 context.Eval(script);
var result = context.GetVariable("result");

Result:
{"fname":"test"}

Expected Result:
{"fname":"test", "lname": null}

When Eval execute and parse JSON, It ignore null value properties. Please help me on this.

Thanks

**Comment by nilproject** [comment]
Thanks for this bugreport. This was a bug in JSON.stringify

**Comment by mahensingh** [comment]
Thank you for your quick response.
May I know when will be the next release and Will the release resolve this issue?
Please update me by comment on ticket.
Thanks

**Comment by nilproject** [comment]
See https://github.com/nilproject/NiL.JS/releases/tag/2.5.1630

**Comment by mahensingh** [comment]
Thank you so much for prompt solution and response.
