### ISSUE TITLE
Protect BaseLibrary content in GlobalContext

### ISSUE THREAD

**Issue by anri-vin** [nilproject/NiL.JS#283]
Hello again.

In continuation of #281 I would like to ask the same question, but now about BaseLibrary stuff, like `Math`, `JSON`. It defined in `GlobalContext` and after execution of any weird script like `Math.abs = undefined;` or even `Math = undefined;` the whole `GlobalContext` became broken and can not be reused in future. 

In first case, I can execute something like `Object.freeze(Math);` for all that kind of stuff just after `GlobalContext` creation. But cant find a way to protect `Math` from being completely erased.

It would be great if you can propose something to achieve that behavior in case it could be done without any code changes. If not - ideal solution (for me) would be a method like `GlobalContext.Lock()` which would make `GlobalContext` and all of it's content completely immutable. But some kind of optional flag at `GlobalContext` ctor to lock just BaseLibrary things would also be great.

**Comment by nilproject** [comment]
Could this be solution of your problem?

**Comment by anri-vin** [comment]
Yes, I think it will work just fine. Thanks!
