### ISSUE TITLE
How to pass object to modules for export

### ISSUE THREAD

**Issue by kitsunoff** [nilproject/NiL.JS#285]
Hello!
Thanks for making this library
I have question with passing delegates to module 
![изображение](https://user-images.githubusercontent.com/58953114/227737892-6f18f7f8-6b81-4262-a52c-00969e7caad0.png)
![изображение](https://user-images.githubusercontent.com/58953114/227737919-519400f7-95fb-4764-a635-91ff9c656c36.png)
![изображение](https://user-images.githubusercontent.com/58953114/227737930-3a03ffb8-bac9-4f8c-8dcc-c519be1d6599.png)

And how pass a static classes to module and contexts?

**Comment by kitsunoff** [comment]
![изображение](https://user-images.githubusercontent.com/58953114/227738053-b39a980e-2392-47d2-aa5a-b983b6876f2c.png)
P.S import is correct
But functions is undefined

**Comment by nilproject** [comment]
You can import only variables, added to [ExportTable](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Module.cs#L35). There is only one way to do this — [invoke `export` command](https://github.com/nilproject/NiL.JS/blob/develop/Tests/ModuleTests.cs#L25).
Also I noticed, that path to the module (second image) is "/base/gu.js", but correct path is "/base/gui.js" (with "i")

**Comment by kitsunoff** [comment]
> You can import only variables, added to [ExportTable](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Module.cs#L35). There is only one way to do this — [invoke `export` command](https://github.com/nilproject/NiL.JS/blob/develop/Tests/ModuleTests.cs#L25).
> 
> Also I noticed, that path to the module (second image) is "/base/gu.js", but correct path is "/base/gui.js" (with "i")

second image its for test

it's possible to pass objects to exporttable from c#?

**Comment by nilproject** [comment]
No. At the moment there is no way to do this

**Comment by kitsunoff** [comment]
> No. At the moment there is no way to do this

i will make a PR tomorrow with this addition

**Comment by kitsunoff** [comment]
https://github.com/nilproject/NiL.JS/pull/286
please check my PR
@nilproject

**Comment by kitsunoff** [comment]
Resolved by my PR
https://github.com/nilproject/NiL.JS/pull/286
