### ISSUE TITLE
Incorrect behaviour of Array.splice

### ISSUE THREAD

**Issue by Markeli** [nilproject/NiL.JS#289]
Method `Array.Splice` works incorrect.

## Step to reproduce

Here is JS script example with comments:
```js
let arr = [1, 2, 3, 4, 5]; // array with 5 items

arr.splice(1, 0, 6); // from index 1 delete 0 items and add 1 new item - 6
```

## Expected result

Expects array `[1, 6, 2, 3, 4, 5]` with 6 items.

## Actual result

Got array `[1, 6, 2, 3, 4]` - array with 5 items and without last item (5)

**Comment by nilproject** [comment]
Thank you

**Comment by Markeli** [comment]
Thanks for the fix!)
