### ISSUE TITLE
Difference in exceptions from JS and from .Net

### ISSUE THREAD

**Issue by anri-vin** [nilproject/NiL.JS#297]
I've noticed a difference in exceptions handling depending where they are coming from. If exception was thrown from JS code, than it has a `message` property. If exception is from .Net - it has `Message` property. It makes exceptions handling a little bit complicated, cause I have to consider in every case where does exceptions comes from, and choose between lower/uppercase `message` property.

JS Exception:
```js
try {
    throw new Error("Message");
} catch (e) {
    console.log(e.message);  //Lowercase property "message"
}
```
.Net Exception
```js
try {
    dotNetObject.throwInsideThatMethod();
} catch (e) {
    console.log(e.Message);  //Uppercase property "message"
}
```

Prior to version 2.5.1591 they both were lowercase, but since 2.5.1591 it is different. Was it made on purpose or is that a bug?

**Comment by nilproject** [comment]
I have checked this. It's a bug that occurred when js-stacktraces support was implemnted. I'll fix this soon

**Comment by anri-vin** [comment]
Thanks for fix! When will you be able to publish a new release?

**Comment by nilproject** [comment]
[Now](https://github.com/nilproject/NiL.JS/actions/runs/6630803883/job/18012984981)
