### ISSUE TITLE
Issue with proxing method

### ISSUE THREAD

**Issue by aienabled** [nilproject/NiL.JS#30]
Hello!
I've found an issue during integration of NiL.JS with mine project (replacing Jurassic, which is good, but too slow).
For example, I need to proxy method
```
void TestMethod(double testValue)
```
in javascript this is executed as

```
testobj.TestMethod(0)
```

but the NiL.JS TypeProxy unable to resolve this call and throws exception, because 0 in NiL.JS is int, but TestMethod need double (TypeProxy.cs:GetMember() line 348).

(the example is oversimplified, in fact I've more complex arguments list)

**Comment by nilproject** [comment]
This bug is actual only for overloaded methods. I will fix it.
You can hide for script some methods that will eliminate ambiguity. See attribute [Hidden].
You can define one method with one argument Core.Arguments. That method will receive raw object with arguments of calling.

**Comment by aienabled** [comment]
Yes, you're right, this is an overloaded method.
Regards!

**Comment by nilproject** [comment]
Fixed. Rev. 671.
