### ISSUE TITLE
Need Best Practices Guides for Performance and Memory Usage

### ISSUE THREAD

**Issue by deimosowen** [nilproject/NiL.JS#300]
Hello NiL.JS Development Team,

We are currently utilizing your NiL.JS JavaScript engine in our project and have encountered a critical challenge related to managing performance and memory usage while executing JavaScript scripts. In our application, users have the ability to run arbitrary scripts through a user interface, which can potentially lead to significant memory consumption and performance degradation. For example, a script that creates a very large array:

```javascript
let array = new Array(1024*1024*1024);
for (let i = 0; i < array.length; i++) {
    array[i] = 0;
}
```

This poses a risk for denial-of-service attacks and other performance-related issues.

We are looking for ways to control and limit memory usage during script execution to prevent such scenarios. In this regard, we have a few questions:

1. Are there any built-in mechanisms in NiL.JS to limit the memory usage of scripts (a "soft limit")? If so, how can we configure or utilize them?

2. Could you recommend best practices or approaches that could help in addressing our issue, specifically for controlling memory consumption of scripts in NiL.JS?

Any help or recommendations you can provide would be greatly appreciated.

**Comment by nilproject** [comment]
i have never thought about that. There is only a built-in way to limit the execution time but there is no built-in way to limit memory usage. But even the implementation of the time limit has some vulnerabilities.
So, you can use DebuggerCallback like it is used in current time limit implemetation, but you need to make some changes. First of all, TryCatch is needs to be patched to prevent it from catching your own LimitExcededException. After that you can enable Debugging and make a DebuggerCallback which will monitor memory usage
