### ISSUE TITLE
Sputnik Test causes non-returning loop

### ISSUE THREAD

**Issue by Oceanswave** [nilproject/NiL.JS#35]
The test runner never proceeds after the following sputnik tests

sputnik\ch15\15.1\15.1.3\15.1.3.1\S15.1.3.1_A1.10_T1.js
sputnik\ch15\15.1\15.1.3\15.1.3.1\S15.1.3.1_A1.11_T1.js
sputnik\ch15\15.1\15.1.3\15.1.3.1\S15.1.3.1_A1.11_T2.js

The conditional variable doesn't seem to increment after the catch.

**Comment by Oceanswave** [comment]
Hm. Looking at the actual tests, it seems that I'm just not patient enough :)

**Comment by nilproject** [comment]
Without debugging these tests much faster
