### ISSUE TITLE
Built-In objects should not rely on native throw/catch exception mechanisms for JS try/catch

### ISSUE THREAD

**Issue by Oceanswave** [nilproject/NiL.JS#36]
Take for instance the following sputnik test:
sputnik\ch15\15.1\15.1.3\15.1.3.1\S15.1.3.1_A1.10_T1.js

each iteration of the loop causes a .net exception to be thrown and caught. This causes the specific tests (and others like it) to take a very long time to run as it is throwing and catching ~65520 .net exceptions.

A different mechanism should be used by the engine to express JS exceptions internally that are only thrown as a .net exception if there isn't an outermost JS based catch.

This would improve performance on these types of tests and overall.

**Comment by nilproject** [comment]
This decision is bad for performance of code that does not throw exceptions

**Comment by Oceanswave** [comment]
Ok, thanks!
