### ISSUE TITLE
unsolvable error

### ISSUE THREAD

**Issue by furesoft** [nilproject/NiL.JS#39]
hi, i use oop.js to create classes.

but when i use it i get this error: NiL.JS.Core.JSException occurred
  HResult=-2146233088
  Message=TypeError: undefined is not callable
  Source=NiL.JS
  StackTrace:
       bei NiL.JS.Expressions.New.ThisSetter.Evaluate(Context context) in c:\Users\Дмитрий\Documents\Projects\NiL.JS\NiL.JS\Expressions\New.cs:Zeile 46.
  InnerException: 

but it works in browser

i really need your help

**Comment by nilproject** [comment]
Because it's bug of oop.js ([see this lines] (https://github.com/oopjs/oopjs/blob/master/src/oopjs/oop.js#L272)). To fix it add this line in oop.js: "var global = function () { return this }();"
