### ISSUE TITLE
invoke more than 1 scripts on 1 context?

### ISSUE THREAD

**Issue by furesoft** [nilproject/NiL.JS#40]
hi, is it possible to run many scripts on 1 context?

when i try with global context dont work, when i try to create a new context, and run js dont work only.

pls help

**Comment by nilproject** [comment]
Hm... maybe, [this sample] (https://github.com/nilproject/NiL.JS/blob/master/NiL.JSTest/Program.cs#L643) can help.

**Comment by furesoft** [comment]
ive tryd with this:
´´´
Context econtext = null;
            Script s = null;

            if (s == null)
            {
                Context.RefreshGlobalContext();
                s = new Script(source);
                s.Invoke();
                econtext = s.Context;
            }
            else
                econtext = new Context(s.Context);
´´´

but same error

**Comment by nilproject** [comment]
Just create Context instance and call Eval(...). When you create new context by other context (new Context(context)) will be created "nested" context similarly to the nested function inside other function.

**Comment by furesoft** [comment]
but when i create an instance of context and run Context.Eval(source);

same error
