### ISSUE TITLE
Date parse problem

### ISSUE THREAD

**Issue by GibbOne** [nilproject/NiL.JS#43]
The following code doesn't work as I expect:

```javascript
NiL.JS.Core.Context ctx = new NiL.JS.Core.Context();
ctx.Eval(@"ret = new Date(Date.parse(""2015-10-27T01:01:01.001Z""));");
Console.WriteLine(ctx.GetVariable("ret").ToString());
```

From Output Windows I receive this:

```
Tue Oct 27 2015 02:17:41 GMT+0100 (ora legale Europa occidentale)
```

If I run this code into chrome console I receive the right date.

```
Tue Oct 27 2015 02:01:01 GMT+0100 (ora solare Europa occidentale)
```

Any suggestions?

**Comment by meriturva** [comment]
I you run the code without seconds the result is the same......
```
NiL.JS.Core.Context ctx = new NiL.JS.Core.Context();
ctx.Eval(@"ret = new Date(Date.parse(""2015-10-27T01:01:00.001Z""));");
Console.WriteLine(ctx.GetVariable("ret").ToString());
```

**Comment by meriturva** [comment]
I found that on NiL.JS/BaseLibrary/Date.cs file on method parseByFormat that you could just use the ISO 8601 feature so:

```
DateTime test = DateTime.Parse(timeStr, null, DateTimeStyles.None);
time = test.Ticks / TimeSpan.TicksPerMillisecond;
```
instead of manual parse the string.
What do you think?

**Comment by nilproject** [comment]
@meriturva DateTime.Parse cannot parse string "1970" (i.e. year only), but it is valid ISO 8601 time value (01-01-1970 00:00:00). No other problems for this

**Comment by nilproject** [comment]
@GibbOne Thank you for your report

**Comment by meriturva** [comment]
Perfect Дмитрий!
are you going to push a new nuget version?

**Comment by GibbOne** [comment]
Thank to you! And also to meriturva.

**Comment by nilproject** [comment]
@meriturva Yes, new version [uploaded](https://www.nuget.org/packages/NiL.JS/1.4.791)

**Comment by GibbOne** [comment]
Sorry but I have the same problem for different hours minutes and seconds.

For example, if I execute this:

```javascript
NiL.JS.Core.Context ctx = new NiL.JS.Core.Context();
ctx.Eval(@"ret = new Date(Date.parse(""2015-10-27T01:02:03.004Z""));");
Console.WriteLine(ctx.GetVariable("ret").ToString());
```

I receive this:

```
Tue Oct 27 2015 02:52:04 GMT+0100 (ora legale Europa occidentale)
```

instead of

```
Tue Oct 27 2015 02:02:03 GMT+0100 (ora solare Europa occidentale)
```

thanks in advance

**Comment by nilproject** [comment]
@GibbOne i got 
> Tue Oct 27 2015 07:02:03 GMT+0600 (RTZ 5 (лето))

(RTZ - Russia Time Zone)
Please, download new version (792) with fixes for this

**Comment by GibbOne** [comment]
It works! Thanks a lot!
Congratulations for this very useful assembly.

**Comment by GibbOne** [comment]
I updated to **2.5.1282** and I got another problem with parse method.

To reproduce try this:
``` c#
Context context = new Context();
var d1 = context.Eval("Date.parse('1970-01-01T00:00:00.000Z')");
Console.WriteLine($"{d1} \t should be 0");
var d2 = context.Eval("Date.parse('1970-01-01T00:00:00.0000000Z')");
Console.WriteLine($"{d2} \t should be 0");    
```
![image](https://user-images.githubusercontent.com/12271500/48915494-255e6280-ee7f-11e8-95fc-a9170ee7026b.png)

Thanks in advance.

**Comment by v12** [comment]
@GibbOne I can't reproduce the issue you're experiencing using your example and the latest version in `develop`. Any chance you can provide additional details about your environment?

**Comment by GibbOne** [comment]
@v12 thanks for the response.

I tried to reproduce using develop branch.
Please look at this:

![image](https://user-images.githubusercontent.com/12271500/49695781-2e01a900-fba0-11e8-9fd9-d170b0332fb3.png)

I inserted my code just after Main declaration in Test project.

I later tested the same code using Moscow time zone, but I get different results even if not corrected.
My time zone is Rome, and I'm using Italian regional settings. 
Feel free to ask me any info.

Have a nice sunday.

**Comment by GibbOne** [comment]
Any news?

**Comment by nilproject** [comment]
@GibbOne, thanks for this bugreport!

**Comment by GibbOne** [comment]
@nilproject, thx you!
