### ISSUE TITLE
How to call method

### ISSUE THREAD

**Issue by Freealism** [nilproject/NiL.JS#44]
Hi,
when I want to call a c#-method from JS I can use a delegate, as described in the examples. This is very fast (I get about 1 mio executions/s).
But how can I do the opposite and call a JS method from C#? For example in jurassic I can do:

``` javascript
i = engine.CallGlobalFunction<int>("test"); /// call the js-method test()
```

Is there an equvalent in NiL.JS? 
Actually I do the following, which is very slow (I get about 30k executions/s):

``` javascript
context.Eval("result = test();");
result = (int)context.GetVariable("result").Value;
```

**Comment by nilproject** [comment]
In NiL.JS no equivalent of this function.
If you need to call one function each time, you can use function Function.MakeDelegate(Type). See [this](https://github.com/nilproject/NiL.JS/blob/version-2.0/Examples/3.%20Methods%20and%20Events/Create%20delegate%20for%20JavaScript%20function.cs) new example.

But, i found one critical bug with it. Please, update NiL.JS to 2.0.860

**Comment by Freealism** [comment]
Wow, this update is great. Thank you very much for your very fast support, I love this Project!
