### ISSUE TITLE
NiL.JS.BaseLibrary.Date.ToDateTime

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#45]
Привет!

Похоже неверно отрабатывает ToDateTime у NiL.JS.BaseLibrary.Date

```
        context.DefineVariable("ddd").Assign(JSValue.Marshal(DateTime.Today));
        var jsDate = (NiL.JS.BaseLibrary.Date)context.GetVariable("ddd").Value;
        Assert.AreEqual(jsDate.ToDateTime(), DateTime.Today);
```

При DateTime.Today равным 25.01.2016, jsDate.ToDateTime() выдает 07.01.2017 21:00

**Comment by nilproject** [comment]
Здравствуйте!
Спасибо, что сообщили о проблеме. Я исправил её в версии [2.0.864](https://www.nuget.org/packages/NiL.JS/2.0.864).
Сообщите, если что-то пойдёт не так.

**Comment by sndanil** [comment]
Все отлично работает, спасибо за оперативность!
