### ISSUE TITLE
Дата в массиве

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#46]
Привет!

Какая-то мистика с массивом происходит:

var engine = new Context();

engine.Eval("var scriptDateArray = [new Date(2015, 1, 1), new Date(2013, 1, 1), new Date(2016, 1, 1), new Date(2000, 3, 1)];");
var scriptDateArray = engine.GetVariable("scriptDateArray");
var jsArray = scriptDateArray.Value as NiL.JS.BaseLibrary.Array;
Assert.IsNotNull(jsArray);
Assert.AreEqual(4, jsArray.length);

Срабатывает второй ассерт, получается что jsArray.length == 0
Воспроизводится если в массиве есть хоть одна дата

**Comment by nilproject** [comment]
Здравствуйте! 
Странно, но у меня не получилось воспроизвести. 
jsArray.length возвращает объект типа JSValue. Возможно, странности появляются из-за того, что сравниваются два объекта, а не напрямую значения. Equals для JSValue переопределён, но попробуйте length преобразовать в int. Например, так: jsArray.length.As<int>()

**Comment by sndanil** [comment]
Разобрался, похоже плагин для студии портил данные. По крайней мере после удаления плагина  тест начал работать. Получается ложная тревога, прошу прощения за беспокойство.
