### ISSUE TITLE
Массив объектов

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#49]
Привет.

Вот такой код:

class TestArrayData
{
    public string getName() {   return "test";  }
}

class TestArray
{
    public TestArrayData[] getArray()   {   return new[] {new TestArrayData(), new TestArrayData()};    }
}

[TestMethod]
public void ObjectArrayTest()
{
    var engine = new Context();
    engine.DefineVariable("obj").Assign(JSValue.Marshal(new TestArray()));
    engine.Eval("obj.getArray().forEach((t) => console.log(t.getName()))");
}

выдает "TypeError: Can not get prototype of null or undefined". Этого же не должно быть?

**Comment by nilproject** [comment]
Да, так быть не должно.
Спасибо!
