### ISSUE TITLE
И снова ToDateTime

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#50]
Привет.

Вот такой код по логике должен отрабатывать:

var today1 = DateTime.Today;
var today2 = new DateTime(today1.Year, today1.Month, today1.Day);
Assert.AreEqual(today1, today2);
Assert.AreEqual(today1.ToUniversalTime(), today2.ToUniversalTime());
context.DefineVariable("today1").Assign(JSValue.Marshal(today1));
context.DefineVariable("today2").Assign(JSValue.Marshal(today2));
var jsToday1 = (NiL.JS.BaseLibrary.Date)context.GetVariable("today1").Value;
var jsToday2 = (NiL.JS.BaseLibrary.Date)context.GetVariable("today2").Value;
Assert.AreEqual(today1, jsToday1.ToDateTime());
Assert.AreEqual(today2, jsToday2.ToDateTime());

Последний ассерт не отрабатывает. Я понимаю, что это происходит потому что у today1.Kind == DateTimeKind.Unspecified. Может правильнее было бы такой случай тоже воспринимать как локальное время?

**Comment by nilproject** [comment]
DateTimeKind.Unspecified настолько странное значение, что правильнее было бы бросать исключение InvalidOperation при попытке маршалинга такого объекта, а не интерпретировать это как какое-то конкретное значение.
А по тесту: добавьте `Assert.AreEqual(today1.ToLocalTime(), today2.ToLocalTime());` и он тоже упадёт
