### ISSUE TITLE
DynamicObject

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#51]
Планируется поддержка [DynamicObject](https://msdn.microsoft.com/ru-ru/library/system.dynamic.dynamicobject%28v=vs.110%29.aspx)? На сколько я вижу сейчас поддержки таких объектов нет, или я ошибаюсь?

**Comment by nilproject** [comment]
Нет, DynamicObject поддерживаться не будет. 
Возможность использовать точку вместо индексаторов со строковым аргументом для получения свойств объектов не компенсирует то падение производительности и разбухание кода, которое происходит при использовании dynamic
