### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by sndanil** [nilproject/NiL.JS#52]
Такой код:

class TestParams
{
    public bool doParams(string test, params object[] testParams)
    {
        return testParams[1].ToString() == "ddd";
    }
}

[TestMethod]
public void ParamsTest()
{
    var engine = new Context();
    engine.DefineVariable("obj").Assign(JSValue.Marshal(new TestParams()));
    var result = engine.Eval("obj.doParams('asd', 2, 'ddd', 4.5)").Value;
    Assert.IsTrue((bool)result);
}

должен отрабатывать?

**Comment by nilproject** [comment]
Нет.
Вызов функции происходит через reflection, а на уровне reflection аргументы с params выглядят как обычный массив. Переменное число параметров можно реализовать с помощью типа Arguments. Но это должен быть единственный аргумент функции
