### ISSUE TITLE
Function type

### ISSUE THREAD

**Issue by LambderFTW** [nilproject/NiL.JS#53]
The Function type seems to have a .call method with an uppercase letter as well.
Which one should I use? Could you make the Arguments optional? I hate writing new Arguments() each time.

Also, is there any way I can use generic types?

**Comment by nilproject** [comment]
.call(...) (lower case) is an implementation of Function.prototype.call(...). You should not use it directly from C# (or any another .NET-language). 
You may use `Call(null)` if arguments are not passed.

At this moment support of generics is very bugged. It's coming soon

**Comment by LambderFTW** [comment]
Alright. Thanks for the tips. I'm really excited about this project.

**Comment by LambderFTW** [comment]
This happened inside _NamespaceProvider.cs_
(I downloaded a zip of the source and built it myself, no modifications)

http://prntscr.com/aalmvg

For some reason it didn't like it when I `JSValue.Wrap`ped something, assigned it and tried to access from JS.

Also, when I tried to `JSValue.Marshal` a `List<Action>` and I try to call `.Add` it throws an exception saying it's not callable. (in the latest nuget version)

**Comment by nilproject** [comment]
For all types, which implements `IList`, engine creates special wrapper `NativeList`. This wrapper provides array-like interface. You may use `push(...)` instead of `Add(...)`. If you want to get a native List interface, you should use `JSValue.Wrap(...)`

Thank for your error report.

**Comment by LambderFTW** [comment]
I want to create a JS object and define its properties then assign to them.
Right now, I'm doing it this way: `JSValue.Assign(JSValue.Marshal(new object()))`
I'd like to know if there's a better alternative.

Also, how can I cast things inside JS? For example, I'd like to cast a function to an `Action<>` and then add it to a `List<Action<>>` all within JS.

**Comment by nilproject** [comment]
Just add this function into List. Function will be converted automatically.

Use `JSValue.Assign(JSObject.CreateObject());`

**Comment by LambderFTW** [comment]
I tried that and it seemed to work a few hours ago.
But now it doesn't for some odd reason.
http://pastebin.com/TcM3Jg08

**Comment by nilproject** [comment]
I think, function cannot be converted to a string implicitly. You trying to add function into List<string>

**Comment by nilproject** [comment]
You trying to do it with develop branch of engine? 
I think, you should use version-2.0 branch or nuget package.

**Comment by LambderFTW** [comment]
I tried both.
Seems it does work for this
`hostlib.DefineProperty("AddAction").Assign(JSValue.Marshal(new Action<Action<string>>(x => LogActions.Add(x))));`
but not for the actual `LogActions.Add` (if I wrap `List<Action<string>> LogActions`)

**Comment by nilproject** [comment]
Already fixed. Added tests 770358a3
