### ISSUE TITLE
Null Exception after updating from 2.0.867 to 2.1.881

### ISSUE THREAD

**Issue by GibbOne** [nilproject/NiL.JS#54]
I updated my project from NiL.JS version 2.0.867 to 2.1.881.

Now, when I try to execute this javascript

``` javascript
function formula () { return new Date(); }

ret = JSON.stringify(formula());
```

I receive this exception

```
"Object reference not set to an instance of an object."
```

with this stacktrace

```
   at NiL.JS.Core.Functions.MethodProxy.ConvertArgs(Arguments source, ConvertArgsOptions options) in C:\Users\polho\Documents\Visual Studio 2013\Projects\NiL.JS\NiL.JS\Core\Functions\MethodProxy.cs:line 533
```

If I update to the old version (2.0.867) the problem disappears.
Is it my mistake?

Thanks a lot for this very useful library!

**Comment by nilproject** [comment]
Thanks for bug report. It was a critical error. Fixed in [2.1.883](https://www.nuget.org/packages/NiL.JS/2.1.883)
