### ISSUE TITLE
ValidateName method in Parser.cs can't handle leading spaces

### ISSUE THREAD

**Issue by airbin** [nilproject/NiL.JS#55]
The ValidateName method on line 271 in Parser.cs can't handle leading spaces like in:

try {

} catch ( e ) {

}

The " e" statement in the catch segment wil throw an exception: Catch block must contain variable name

The ValidateName method should filter out the leading spaces like:

```
    public static bool ValidateName(string code, ref int index, bool checkReservedWords, bool allowEscape, bool strict)
    {
        int j = index;
        while (code[j] == ' ')
        {
            j++;
        }
```

**Comment by nilproject** [comment]
Thank for this report. This error will be fixed in next release.
ValidateName should not handle spaces. It is critical part of logic. Spaces should be skipped while parsing.

**Comment by airbin** [comment]
Thank you for your quick reponse and solution.
