### ISSUE TITLE
var/let bugs

### ISSUE THREAD

**Issue by Chamberlain91** [nilproject/NiL.JS#56]
```
function f() {
    {
        let x;
        console.log(x);
        {
            // okay, block scoped name
            const x = "sneaky";
            console.log(x);
            // error, const
            x = "foo";
            console.log(x);
        }
        // error, already declared in block
        let x = "inner";
        console.log(x);
    }
}

f();
```

let x = "inner"; is not supposed to work because its redefined, isn't it?

Also,

Example 3 of implace, works as expected with let, but doesn't with var. Is this intentional? I don't know the specifics of var vs let.

Also, quick question. It seems that es6 import/export isn't supported. Is there a list of features that aren't supported in NIL?

**Comment by nilproject** [comment]
Yes, `let x = "inner";` should throw an exception, but don't. It's bug and it will be fixed.

Parameter `inplace` of eval adds code to the script without creating a block. As if the script and the first argument of the eval are parts of one script. It will be renamed.

`import/export`: I'm working on it. I think, work will be completed this week.

**Comment by Chamberlain91** [comment]
I understand how `inplace` worked. I'll be happy to help test bugs for you.
I'll be very excited for import/export.
