### ISSUE TITLE
[question] Call function of object

### ISSUE THREAD

**Issue by larsalbrecht** [nilproject/NiL.JS#58]
Hi,

I tested your library, but Im confused.

I have one js-file:
example.js

```
Module module = null;
var fileContent = File.ReadAllText("example.js");
fileContent += Environment.NewLine + "var myObject = new MyObject();";
module = new Module(fileContent);
module.Run();
var myObject = module.Context.GetVariable("myObject");
```

I get an Object from type ObjectWrapper. I can read out variables with: 

```
Console.WriteLine(myObject["someVariable"]);
```

But how can I call functions from the object?

**Comment by nilproject** [comment]
Hi.

It's [easy](https://github.com/nilproject/NiL.JS/blob/version-2.2/Examples/4.%20Methods%20and%20Events/Call%20JavaScript%20function%20directly.cs#L18). Just add `using NiL.JS.Extensions;`.

Also you can get raw value from variable and convert it to Function: `(module.Context.GetVariable("myFunc").Value as Function).Call(null)`

**Comment by larsalbrecht** [comment]
Thank you, I missed this example.
