### ISSUE TITLE
JSValue.Is<long>() always returns false

### ISSUE THREAD

**Issue by xpg934** [nilproject/NiL.JS#60]
На мой взгляд тут вкралась ошибка.
В JSValueExtensions.cs метод Is<T>() для Int64 и UInt64 всегда возвращает false, однако для Int32 или Int16 проверяет значение и возвращает правильное true/false, в зависимости от возможности конвертации. Но ведь ничего не мешает, например, число 1234 представить как long?
Более того, метод As<T>() вполне нормально отработает при вызове As<long>() если в JSValue будет число 1234 или подобное.

Предлагаю доделать Is<T>() чтобы возвращал true для T = long, если значение в этот long влезает.

**Comment by nilproject** [comment]
Спасибо за предложение!

**Comment by xpg934** [comment]
Спасибо за фикс :) Только наверное тоже самое надо добавить и для UInt64, а то получается что As<ulong> способен нормально вернуть значение, а Is<ulong> всегда возвращает false.

**Comment by nilproject** [comment]
Хорошо
