### ISSUE TITLE
Sandboxing and execution time limit

### ISSUE THREAD

**Issue by sergeystoma** [nilproject/NiL.JS#63]
Is there a built-in or a suggested way to implement run time limiting?

**Comment by nilproject** [comment]
You can use method `Module.Run(timeLimit)`. It will abort execution when time is over and no one external call is executing. So it's guarantees that all external calls (include calls into other JS modules) will not be aborted with TimeoutException. If you wish to abort external calls too, than maybe you should call  `Module.Run()` from different thread (for example via Task) and aborts it from main thread (or any other)
