### ISSUE TITLE
Static fields won't allow for multithreaded operation

### ISSUE THREAD

**Issue by sergeystoma** [nilproject/NiL.JS#64]
There are a few places in NIL.JS that take advantage of static fields for caching/optimizations, for example MethodProxy._wrapperCache, TypeProxy proxies dictionaries. Unfortunately that causes issues when attempting to run contexts concurrently. Also, static list of runnable contexts (in non-portable versions) appears to be failing sometimes when context is being reused. Test code below would randomly produce one of the two exceptions:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Type "NilJs.A" already proxied.
   at NiL.JS.Core.Interop.TypeProxy..ctor(Type type, JSObject prototype) in C:\Projects\tests\NiL.JS\Core\Interop\TypeProxy.cs:line 98
   at NiL.JS.Core.Interop.TypeProxy.GetPrototype(Type type, Boolean create) in C:\Projects\tests\NiL.JS\Core\Interop\TypeProxy.cs:line 367
```

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Context is not running
   at NiL.JS.Core.Context.Deactivate() in C:\Projects\tests\NiL.JS\Core\Context.cs:line 384
   at NiL.JS.Core.Context.Eval(String code, Boolean suppressScopeCreation) in C:\Projects\tests\NiL.JS\Core\Context.cs:line 669
```

Test code:

```
class Program
{
    static void Main(string[] args)
    {
        Action task = () =>
        {
            var context = new Context();
            context.Eval("function test(a) { a.F(); }");

            var a = new A();

            for (var i = 0; i < 1000; ++i)
            {
                context.GetVariable("test").As<Function>().Call(new Arguments() { JSValue.Wrap(a) });
            }
        };

        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
        Task.WaitAll(Task.Run(task), Task.Run(task));
    }
}

public class A
{
    public void F()
    {
        Console.WriteLine(Thread.CurrentThread.ManagedThreadId);
    }
}
```

**Comment by nilproject** [comment]
It's known bug. So, this engine is singlethreaded as many other JS-engines. V8 singlethreaded too.
I will try to fix it, but i cannot promise it

**Comment by sergeystoma** [comment]
Could creating a new "container" to hold global engine state be the way to go? Things like context cache, type proxy mappings, etc, could move into it, but there is a disadvantage that state object would have to be passed around now. It is also a bit unclear what to do about global references like Boolean.True/False, JsObject.GlobalPrototype, seems like they would need to move as well. If that sounds about right and compatible with the project vision I can probably take a stab at the conversion when have a free moment...

Fantastic job by the way! Software product that we are working on relies on the js interpreter for users to write their own business rules. Those rules are generally light on actual js logic, but instead are _very_ interop heavy. We've been using Jint for a while, and NiL.JS is 10x faster. One rule that I've been testing on went from 40 seconds to 3.5s run time.

**Comment by nilproject** [comment]
This code (and another more complex) do not produce any error after this changes. I think, problem was resolved.
