### ISSUE TITLE
NiL.JS does not return the expected result

### ISSUE THREAD

**Issue by tranb3r** [nilproject/NiL.JS#66]
This javascript is not properly executed by NiL.JS (JSException):

`var script = @"
function foo() {
    var e = 'ab';
    var i = e.replace(/[a-z]/g, function(f) {
            console.log(f);
            return String.fromCharCode((f <= 'Z' ? 90 : 122) >= (f = (f.charCodeAt(0)) % 26 + (f <= 'Z' ? 90 : 122) - 26) ? f : f - 26);
        });
    return i
}
";
            var context = new Context();
            context.Eval(script);
            var result = context.GetVariable("foo").As<Function>().Call(null).As<string>();
`

But it works with Jint (expected result is 'st').
Any idea what's happening ?

**Comment by nilproject** [comment]
Thank you for your bug report!

**Comment by tranb3r** [comment]
Thank YOU for the quick fix and nuget release ! It works perfectly :)
