### ISSUE TITLE
NuGet version 2.3.950 does not contain portable libs

### ISSUE THREAD

**Issue by tranb3r** [nilproject/NiL.JS#68]
Hi,

It looks like the new nuget package version 2.3.950 does not contain anymore portable libs.
Is it on purpose ? Or an error when packing the nuget ?

Thanks
tranb3r

**Comment by tranb3r** [comment]
I've just seen the .net core release of NiL.JS...
I guess I could use it in my portable lib. 
However I'm on netstandard 1.3 and NiL.JS is netstandard 1.6.

Does NiL.JS require netstandard 1.6 api, or could you change it to depend on a lower netstandard version (<= 1.3) for greater compatibility with other libs ?

Thanks again
tranb3r

**Comment by nilproject** [comment]
Thanks for this report.
Yes, absence of assemblies was an error. I fixed it for version 2.3.955. It should be available in nuget in the near future.
No, I cannot downgrade version of netstandard for .Net Core project.

**Comment by nilproject** [comment]
@tranb3r [current version](https://www.nuget.org/packages/NiL.JS.NetCore/) requires NETStandard 1.3

**Comment by tranb3r** [comment]
Cool ! I've just tested it and it works in my netstandard1.3 project :)
Thanks
