### ISSUE TITLE
How to use an ExpandObject variable in a script?

### ISSUE THREAD

**Issue by GibbOne** [nilproject/NiL.JS#69]
I need to use ExpandoObject as variable inside a script.
But script can't access dynamic properties of the ExpandObject. 

In the example below:

```
        NiL.JS.Core.Context cts = new NiL.JS.Core.Context();

        dynamic e = new ExpandoObject();
        e.a = 1;
        cts.DefineVariable("x").Assign(JSValue.Wrap(e));
        var ret = cts.Eval("x.a");
```

the "ret" variable is **undefined** instead of **1**.

**Comment by nilproject** [comment]
Support for ExpandoObject not yet implemented. Use [this class](https://gist.github.com/nilproject/63a499e00b3340e3a043eec4e6830071) for a temporary solution. I will implement this in future releases

**Comment by GibbOne** [comment]
Sorry for the delay.
It works! Thx a lot.

**Comment by lorond** [comment]
Not just `ExpandoObject` but `IDynamicMetaObjectProvider` support would be great.
