### ISSUE TITLE
Indexers not supported for CLR types

### ISSUE THREAD

**Issue by lorond** [nilproject/NiL.JS#70]
Test case:

    void Main()
    {
        var script = @"
        console.log(test.Prop); // prop
        console.log(test[0]); // undefined
        ";

        var s = new Context();

        s.DefineVariable("test").Assign(JSValue.Marshal(new TestIndexer())); // .Wrap not works too
        s.Eval(script);
    }

    public class TestIndexer
    {
        public string Prop
        {
            get { return "prop"; }
        }
        public string this[int key]
        {
            get { return "integer: " + key; }
        }
        public string this[object key]
        {
            get { return "object: [" + (key == null ? "null" : key.GetType().Name) + "] " + key; }
        }
    }

**Comment by nilproject** [comment]
You can use method "get_Item(...)" for objects with indexers. For this case `test.get_Item(0)` will return `integer: 0` and `test.get_Item('0')` will return `object: [JSValue] 0`.

This feature can have a big impact on performance. I will implement this as a optional behavior.

**Comment by windischb** [comment]
I would need this feature too!
I'ts currently the only thing which prevents me to use NiL.JS...

**Comment by nilproject** [comment]
This feature is implemented. Use `UseIndexersAttribute` with custom types to enable this feature or switch `GlobalContext.IndexersSupportMode` to `ForceEnable` to enable this feature for all types.

**Comment by windischb** [comment]
Works for me! Thanks!
