### ISSUE TITLE
__proto__ && foreach

### ISSUE THREAD

**Issue by Wassili-Hense** [nilproject/NiL.JS#73]
```C#
    [TestMethod]
    public void T99() {
      var proto = JSObject.CreateObject();
      proto["B"] = 1;
      var obj = JSObject.CreateObject();
      obj["A"] = 2;
      obj.__proto__ = proto;
      var L = obj.ToArray();
      Assert.AreEqual(2, L.Length);  // ??
    }
```
JS знаю не очень, а однозначного ответа не нашёл. Должен "B" оказаться в "L" или нет?

**Comment by nilproject** [comment]
В данном случае имеет значение не то, как перебор свойств описан в стандарте JS, а то, как он реализован конкретно в этом движке. Здесь перечисляются только собственные свойства, поэтому "B" не будет в "L".
[Реализация for..in](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Statements/ForIn.cs#L291) переходит к прототипу когда заканчиваются свойства объекта. Таким образом достигается соответствие стандарту JS.
