### ISSUE TITLE
JSON.parse infinity loop

### ISSUE THREAD

**Issue by Wassili-Hense** [nilproject/NiL.JS#74]
Оно конечно мой косяк, но здесь хотелось бы ошибку получать.
```C#
    [TestMethod]
    public void T98() {
      string json = "\"a\":0";
      var a0=NiL.JS.BaseLibrary.JSON.parse(json);
    }
```
Вешается на parse. Если добаваляю reviewer, то он бесконечно вызывается с аргументом (null, "a").

**Comment by nilproject** [comment]
Это всё таки моя ошибка. Оно должно кидать исключение, а не зависать.
Спасибо!
