### ISSUE TITLE
Double parsing bug

### ISSUE THREAD

**Issue by RunDevelopment** [nilproject/NiL.JS#76]
When I tried parsing the number 1.7158203125 the result was 4398046511105.716.

So played a little with this and found out that every number ending with .7158203125 will be parsed wrong and I spotted a pattern:
For every number _d_ ending with .7158203125 the result will be:
_d_ > 0:  4398046511104 + _d_
_d_ < 0: -4398046511104 + _d_

The bug disappears for large number >= 1850000000 before the .7158203125 ending. (Maybe because the ending is cut off?)

This bug does not occur in other environments like Python or Google Chrome and it doesn't seem to be related to .Nets `Double.Parse` function.

**Comment by nilproject** [comment]
Thank! This bug is already fixed, but version with this fix not published yet. See #75 for additional info.
It's because this engine uses custom implementation of Double.Parse.
