### ISSUE TITLE
Anonymous class

### ISSUE THREAD

**Issue by Wassili-Hense** [nilproject/NiL.JS#78]
Категорично приветствую.
[Здесь](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/class) говорят, что анонимные классы в JS разрешены.
```C#
JSC.Context ctx = new JSC.Context(true);
var ctor = ctx.Eval("class { constructor(){ this.a=1;} Tick(){ this.a++; } }") as JSL.Function;
  // JSC.JSException, Message=SyntaxError: Class must have name (1:1)
```
У меня код пишет пользователь и при дублировании имён возможны неприятные последствия.

**Comment by nilproject** [comment]
Разрешены. Но для этого они должны быть rvalue, То есть, они должны быть в правой части присваивания.
```c#
Context ctx = new Context(true);
var ctor = ctx.Eval("var ctor; ctor = class { constructor(){ this.a=1;} Tick(){ this.a++; } }");
Console.WriteLine(ctor); // class { constructor() { this.a=1;}Tick() { this.a++; } }
```

**Comment by nilproject** [comment]
Могу предложить использовать [механизм модулей](https://github.com/nilproject/NiL.JS/blob/version-2.4/Examples/1.%20Using%20modules/Custom%20module%20resolver.cs), чтобы избежать конфликта имён.
