### ISSUE TITLE
RegExp not Work

### ISSUE THREAD

**Issue by zh3305** [nilproject/NiL.JS#84]
```javascript
for (var i = 0; i < arguments.length; i++) {
                    if (arguments[i] != undefined) {
                        var reg = new RegExp("({[" + i + "]})", "g");
                        result = result.replace(reg, arguments[i]);
                    }
     }
```

**Comment by nilproject** [comment]
What an initial string in 'result'?

**Comment by zh3305** [comment]
result="hello {0} "
arguments=["word"]

**Comment by nilproject** [comment]
This regexp is incorrect. {...} defines a repeating of previous element. [...] defines a set of characters. (...) stores a matched value into internal slot. If you want to use regexp for this, you should to escape this symbols with '\\'.
But you don't need regexp for this. Use simple string without regexp.
```JS
result.replace("{" + i + "}", arguments[i])
```

Also you can use [string interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals):
```JS
result = `hello ${ arguments[0] }`;
```
but this don't allows generate template dynamically.
