### ISSUE TITLE
Arrow function "must have name"

### ISSUE THREAD

**Issue by andy-hanson** [nilproject/NiL.JS#86]
Using NiL.JS.NetCore Version=2.4.1056

```
var context = new NiL.JS.Core.Context();
context.Eval(@"() => 1");
```

Expected: Evaluates to a function, just like `node -p "() => 1"`

Actual: `Unhandled Exception: NiL.JS.Core.JSException: SyntaxError: Function must have name (1:1)`

**Comment by nilproject** [comment]
Thanks
