### ISSUE TITLE
.__proto__ does not work properly

### ISSUE THREAD

**Issue by RunDevelopment** [nilproject/NiL.JS#92]
\_\_proto\_\_ will throw a type error on some type. e.g:

```js
var s = "";
s.__proto__
```

This will throw:
```
TypeError: Can not call function "get___proto__" for object of another type.
```

Same for:

```js
var n = 5;
n.__proto__
```

Directly using `new String()` and `new Number()` work as expected; no error.

\_\_proto\_\_ seems to work everywhere else just fine.

**Comment by nilproject** [comment]
Thanks!
