### ISSUE TITLE
Arguments.GetEnumerator() does not enumerate [DoNotEnumerate]s

### ISSUE THREAD

**Issue by RunDevelopment** [nilproject/NiL.JS#93]
This might not sound like an issue but it is. Consider this:

```c#
var args = new Arguments();
for (int i = 0; i < 10; i++)
    args.Add(BaseLibrary.Number.POSITIVE_INFINITY);
var e = args.GetEnumerator();
while (e.MoveNext())
    System.Console.WriteLine(e.Current);
```

### Expected output:
`[0, NaN]`  ...  `[9, NaN]`

### Actual output:
None. 
`e.MoveNext()` always returns false, because BaseLibrary.Number.POSITIVE_INFINITY is a [DoNotEnumerate]. FYI args.Length is 10.
I choose 10 items to demonstrate that the problem is not fixed by simply deleting the code to hide [DoNotEnumerate]s in a0 - a4.

Accessing them by index, of course, doesn't have this problem.

**Comment by nilproject** [comment]
Thanks!

**Comment by nilproject** [comment]
It turned out that this is the expected behavior. Fix for this issue leads to errors.

**Comment by RunDevelopment** [comment]
What kind of errors do you get?

**Comment by nilproject** [comment]
Tests `10.6-10-c-ii-1` and `10.6-10-c-ii-2` fails.

**Comment by nilproject** [comment]
This bug can be fixed, but with performance penalty for common case. After 523732a you can clone items before adding to make the behavior expected.

**Comment by RunDevelopment** [comment]
How about we just change the Enumerator?
We could say: If the index is an integer `>= 0` and `< length` then we will enumerate it no matter what.
I currently running the tests but it seems like this works

**Comment by RunDevelopment** [comment]
`10.6-10-c-ii-1` and `10.6-10-c-ii-2` passed

**Comment by nilproject** [comment]
No, we cannot change the Enumerator. This method used for `for-in` and `for-of`. This behavior is checked by tests too.

I working on fix for it.

**Comment by RunDevelopment** [comment]
Ok
